import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/rose-pine.toml"
]
[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.95

[window.padding]
x = 15
y = 15

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
term = "xterm-256color"
