-- require("flash").jump({
--     remote_op = {
--         restore = true,
--         motion = true,
--     },
--     modes = {
--         char = {
--             jump_labels = true
--         }
--     }
-- })
